name: 3D Contrib Profile
on:
  schedule: [{cron: "0 0 * * *"}]   # daily
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generate 3D profile" || echo "No changes"
          git push
